- name: tags
  hosts: localhost
  tasks:
    - name: Centos
      debug:
        msg: hello
        tags:
          - centos


#- name: Tags
#  hosts: localhost
#  tasks:
#    - name: CentOS
#      debug:
#        msg: CentOS
#      tags:
#        - centos
#    - name: Ubuntu
#      debug:
#        msg: Ubuntu
#      tags:
#        - ubuntu